### ISSUE TITLE
How to check the real reads cover an SNP in a cell?

### ISSUE THREAD

**Issue by jiehuichen** [single-cell-genetics/cellsnp-lite#107]
Hi Xianjie,

Thanks for your great efforts on the cellsnp-lite.

Recently, I met an issue about checking the reads cover an SNP.

For "1/0:1:11:0:39,33,380:0,10,0,1,0", which means this cell is a heterozygote, how to check the real reads cover this SNP?
Can we view these reads in IGV or just grab all the reads related to this cell's SNP by samtools?

Best,

**Comment by hxj5** [comment]
Hi, yes, you can extract the reads by samtools and then view them in IGV.

To extract reads covering a SNP and output to a BAM file (**assuming the SNP's position is chr1:100000**):
```
samtools view -h -b  "input_BAM"  chr1:100000  >  "output_BAM"
samtoos index "output_BAM"
```

If you only want to extract SNP reads in specific cell (**assuming cell barcode is XXX-1 and cell tag is CB**):
```
samtools view -h -b  -d CB:XXX-1  "input_BAM"  chr1:100000  >  "output_BAM"
samtoos index "output_BAM"
```

Then you can load the output BAM file above into IGV to view the reads.

**Comment by hxj5** [comment]
Hi, the inconsistency of read counts between samtools and cellsnp-lite is probably due to the different filtering settings of the two tools, e.g., by default, cellsnp-lite will filter some low-quality reads (please check `--exclFLAG` option) while samtools do not. To make the filtering settings the same, you can use `-F` option in samtools view.

Yes, generally speaking, adding "--minMAF 0.1 --minCOUNT 20" is recommended to reduce false positives.

**Comment by jiehuichen** [comment]
Got you, many thanks.
