### ISSUE TITLE
Multiple Samples Per Individual Query

### ISSUE THREAD

**Issue by sxf-ux** [single-cell-genetics/cellsnp-lite#126]
Hi I had a question.

I have 10x single cell sequencing data. I have multiple samples per individual. Ive read previous questions on similar issues here but im still a little confused.

how would I run cellsnp-lite ? I have seperate bam files and seperate barcodes for each samples. so what would the command line code be?

Also, I would want my cell barcodes to follow a structure of `barcode_sample` as I have that structure for other cell barcodes in other analysis. how would cellsnp-lite recognise the barcodes belonging to one samples vs another?

im running this as a prerequisite of running mquad for mitochondria variant calling so in theory, id want one vcf file that accounts for all of my samples together per individual.

thank you in advance

**Comment by hxj5** [comment]
Hi, I assume you want to get the SNP results per individual instead of per sample, you may first update the `CB` tag in (sample) BAM files and also corresponding barcode file (to follow a structure of `barcode_sample`), then merge the BAM files per individual. The cmdline would be like (per individual) `cellsnp-lite -s <merged BAM file> -b <merged barcode file> ...... <other options>`

**Comment by sxf-ux** [comment]
Yes I did. Thank you for the reply. I'll try this out !

**Comment by sxf-ux** [comment]
it worked. thank you !
