### ISSUE TITLE
cellsnp-lite on other species, organism

### ISSUE THREAD

**Issue by dongwankimlab** [single-cell-genetics/cellsnp-lite#134]
Hi, thank you for nice software. I have a quick question. 

Would it be possible to try cellsnp-lite on 10x scRNA-seq & Illumina bulk RNA-seq data from diploid chimpanzee sample?

Thank you in advance.

**Comment by hxj5** [comment]
Hi, generally speaking, the answer is yes. If you have a list of (common) SNPs at hand, you may run mode 1 (mode 1a for 10x scRNA-seq data and 1b for bulk data), otherwise, you may run mode 2 to genotype whole chromosomes (mode 2a for 10x data and 2b for bulk data; and set proper `--chrom` option). For detailed instructions on each mode, you may check out the section [Quick Usage](https://cellsnp-lite.readthedocs.io/en/latest/main/manual.html#quick-usage-for-single-cell-or-bulk-rna-seq-data) in the manual.

**Comment by dongwankimlab** [comment]
Thank you very much. I'll try!
