### ISSUE TITLE
unable to install cellsnp-lite via conda: out of memory

### ISSUE THREAD

**Issue by nanu23333** [single-cell-genetics/cellsnp-lite#142]
When I attempted to install cellsnp-lite using Conda, I encountered the following error:

`Solving environment: - Out of memory allocating 18446744071562067977*4 bytes!  `
`Aborted (core dumped)`
It also took a very long time before this error appeared.

I tried running` conda clean --all `beforehand to clear any cached data, but unfortunately, it did not resolve the issue.

I would greatly appreciate your help in resolving this problem. Thank you!

**Comment by hxj5** [comment]
Hi, it seems an issue of conda instead of cellsnp-lite. The error message means that the machine ran out of memory, probably because the solve was too complex ([similar issue](https://www.biostars.org/p/9589824/)).

You may try:
- create a new conda env and then install cellsnp-lite in it.
- use [memba](https://github.com/mamba-org/mamba) (a reimplementation of the conda package manager; much memory-efficient) instead of conda.
- use another machine/server with a larger memory.

**Comment by nanu23333** [comment]
thanks for your swift reply, I will try again!
